
ad_perf_stats_schema = [
    bigquery.SchemaField('_insert_time', 'TIMESTAMP'),
    bigquery.SchemaField('ad_account_id', 'STRING'),
    bigquery.SchemaField('ad_id', 'STRING'),
    bigquery.SchemaField('start_time', 'DATE'),
    bigquery.SchemaField('end_time', 'DATE'),
    bigquery.SchemaField('impressions', 'INT64'),
    bigquery.SchemaField('swipes', 'INT64'),
    bigquery.SchemaField('quartile_1', 'INT64'),
    bigquery.SchemaField('quartile_2', 'INT64'),
    bigquery.SchemaField('quartile_3', 'INT64'),
    bigquery.SchemaField('view_completion', 'INT64'),
    bigquery.SchemaField('attachment_quartile_1', 'INT64'),
    bigquery.SchemaField('attachment_quartile_2', 'INT64'),
    bigquery.SchemaField('attachment_quartile_3', 'INT64'),
    bigquery.SchemaField('attachment_view_completion', 'INT64'),
    bigquery.SchemaField('attachment_total_view_time_millis', 'INT64'),
    bigquery.SchemaField('frequency', 'FLOAT64'),
    bigquery.SchemaField('avg_view_time_millis', 'INT64'),
    bigquery.SchemaField('swipe_up_percent', 'FLOAT64'),
    bigquery.SchemaField('attachment_frequency', 'FLOAT64'),
    bigquery.SchemaField('attachment_avg_view_time_millis', 'INT64'),
    bigquery.SchemaField('uniques', 'INT64'),
    bigquery.SchemaField('attachment_impressions', 'INT64'),
    bigquery.SchemaField('attachment_uniques', 'INT64'),
    bigquery.SchemaField('ios_installs', 'INT64'),
    bigquery.SchemaField('android_installs', 'INT64'),
    bigquery.SchemaField('total_installs', 'INT64'),
    bigquery.SchemaField('spend', 'INT64'),
    bigquery.SchemaField('view_time_millis', 'INT64'),
    bigquery.SchemaField('video_views', 'INT64'),
    bigquery.SchemaField('conversion_purchases', 'INT64'),
    bigquery.SchemaField('conversion_purchases_value', 'INT64'),
    bigquery.SchemaField('conversion_save', 'INT64'),
    bigquery.SchemaField('conversion_start_checkout', 'INT64'),
    bigquery.SchemaField('conversion_add_cart', 'INT64'),
    bigquery.SchemaField('conversion_view_content', 'INT64'),
    bigquery.SchemaField('conversion_add_billing', 'INT64'),
    bigquery.SchemaField('conversion_searches', 'INT64'),
    bigquery.SchemaField('conversion_level_completes', 'INT64'),
    bigquery.SchemaField('conversion_app_opens', 'INT64'),
    bigquery.SchemaField('conversion_page_views', 'INT64'),
    bigquery.SchemaField('screen_time_millis', 'INT64'),
    bigquery.SchemaField('avg_screen_time_millis', 'INT64')
]

ad_squads_stats_schema = [
    bigquery.SchemaField('_insert_time', 'TIMESTAMP'),
    bigquery.SchemaField('ad_account_id', 'STRING'),
    bigquery.SchemaField('ad_squad_id', 'STRING'),
    bigquery.SchemaField('start_time', 'DATE'),
    bigquery.SchemaField('end_time', 'DATE'),
    bigquery.SchemaField('impressions', 'INT64'),
    bigquery.SchemaField('swipes', 'INT64'),
    bigquery.SchemaField('quartile_1', 'INT64'),
    bigquery.SchemaField('quartile_2', 'INT64'),
    bigquery.SchemaField('quartile_3', 'INT64'),
    bigquery.SchemaField('view_completion', 'INT64'),
    bigquery.SchemaField('attachment_quartile_1', 'INT64'),
    bigquery.SchemaField('attachment_quartile_2', 'INT64'),
    bigquery.SchemaField('attachment_quartile_3', 'INT64'),
    bigquery.SchemaField('attachment_view_completion', 'INT64'),
    bigquery.SchemaField('attachment_total_view_time_millis', 'INT64'),
    bigquery.SchemaField('frequency', 'FLOAT64'),
    bigquery.SchemaField('avg_view_time_millis', 'INT64'),
    bigquery.SchemaField('swipe_up_percent', 'FLOAT64'),
    bigquery.SchemaField('attachment_frequency', 'FLOAT64'),
    bigquery.SchemaField('attachment_avg_view_time_millis', 'INT64'),
    bigquery.SchemaField('uniques', 'INT64'),
    bigquery.SchemaField('attachment_impressions', 'INT64'),
    bigquery.SchemaField('attachment_uniques', 'INT64'),
    bigquery.SchemaField('ios_installs', 'INT64'),
    bigquery.SchemaField('android_installs', 'INT64'),
    bigquery.SchemaField('total_installs', 'INT64'),
    bigquery.SchemaField('spend', 'INT64'),
    bigquery.SchemaField('view_time_millis', 'INT64'),
    bigquery.SchemaField('video_views', 'INT64'),
    bigquery.SchemaField('conversion_purchases', 'INT64'),
    bigquery.SchemaField('conversion_purchases_value', 'INT64'),
    bigquery.SchemaField('conversion_save', 'INT64'),
    bigquery.SchemaField('conversion_start_checkout', 'INT64'),
    bigquery.SchemaField('conversion_add_cart', 'INT64'),
    bigquery.SchemaField('conversion_view_content', 'INT64'),
    bigquery.SchemaField('conversion_add_billing', 'INT64'),
    bigquery.SchemaField('conversion_searches', 'INT64'),
    bigquery.SchemaField('conversion_level_completes', 'INT64'),
    bigquery.SchemaField('conversion_app_opens', 'INT64'),
    bigquery.SchemaField('conversion_page_views', 'INT64'),
    bigquery.SchemaField('screen_time_millis', 'INT64'),
    bigquery.SchemaField('avg_screen_time_millis', 'INT64')
]

campaign_dictionary_schema = [
    bigquery.SchemaField('_insert_time', 'TIMESTAMP'),
    bigquery.SchemaField('campaign_id', 'STRING'),
    bigquery.SchemaField('name', 'STRING'),
    bigquery.SchemaField('ad_account_id', 'STRING'),
    bigquery.SchemaField('updated_at', 'DATE'),
    bigquery.SchemaField('created_at', 'DATE'),
    bigquery.SchemaField('status', 'STRING'),
    bigquery.SchemaField('daily_budget_micro', 'INT64'),
    bigquery.SchemaField('objective', 'STRING'),
    bigquery.SchemaField('ios_app_id', 'STRING'),
    bigquery.SchemaField('android_app_url', 'STRING'),
    bigquery.SchemaField('start_time', 'DATE')
]

ad_squad_dictionary_schema = [
    bigquery.SchemaField('_insert_time', 'TIMESTAMP'),
    bigquery.SchemaField('ad_account_id', 'STRING'),
    bigquery.SchemaField('campaign_id', 'STRING'),
    bigquery.SchemaField('adsquad_id', 'STRING'),
    bigquery.SchemaField('name', 'STRING'),
    bigquery.SchemaField('updated_at', 'DATE'),
    bigquery.SchemaField('created_at', 'DATE'),
    bigquery.SchemaField('status', 'STRING'),
    bigquery.SchemaField('type', 'STRING'),
    bigquery.SchemaField('placement', 'STRING'),
    bigquery.SchemaField('billing_event', 'STRING'),
    bigquery.SchemaField('bid_micro', 'INT64'),
    bigquery.SchemaField('auto_bid', 'BOOL'),
    bigquery.SchemaField('target_bid', 'BOOL'),
    bigquery.SchemaField('daily_budget_micro', 'INT64'),
    bigquery.SchemaField('start_time', 'DATE'),
    bigquery.SchemaField('optimization_goal', 'STRING'),
    bigquery.SchemaField('delivery_constraint', 'STRING'),
    bigquery.SchemaField('pacing_type', 'STRING')

]

ads_dictionary_schema = [
    bigquery.SchemaField('_insert_time', 'TIMESTAMP'),
    bigquery.SchemaField('ad_account_id', 'STRING'),
    bigquery.SchemaField('ad_id', 'STRING'),
    bigquery.SchemaField('name', 'STRING'),
    bigquery.SchemaField('ad_squad_id', 'STRING'),
    bigquery.SchemaField('creative_id', 'STRING'),
    bigquery.SchemaField('updated_at', 'DATE'),
    bigquery.SchemaField('created_at', 'DATE'),
    bigquery.SchemaField('status', 'STRING'),
    bigquery.SchemaField('type', 'STRING'),
    bigquery.SchemaField('render_type', 'STRING'),
    bigquery.SchemaField('review_status', 'STRING')
]
